version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_books
    environment:
      - MONGO_INITDB_DATABASE=books
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - mongo-net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb_books
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge